# Generated by Django 3.2.16 on 2024-01-25 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.query


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('full_address', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.query.Prefetch, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
